Fixes/article pdf services
Madhavkabra/Saloni-Content-Writer-Portfolio pull request #2
Opened 2023-03-28 11:08 UTC by Atharva-techstuff

2023-03-28 11:11 UTC, Madhavkabra commented on src/components/PDFViewer/PDFViewer.js
> +    const width = window.innerWidth;
Needs to be improvised into separate function inside utils folder

2023-03-29 09:12 UTC, Madhavkabra requested changes

2023-03-29 09:12 UTC, Madhavkabra commented on src/components/Chips/Chips.js
> +      selectedCategories.splice(selectedCategories.indexOf(title), 1);
Do not mutate the state directly

2023-03-29 09:12 UTC, Madhavkabra commented on src/pages/articles/Articles.js
> +  const a1 = urlPath?.split('=');
Improvise naming

2023-03-29 09:12 UTC, Madhavkabra commented on src/pages/articles/Articles.js
> +          selectedCategories.length == 0
No ==

2023-03-29 10:34 UTC, chandreshpatidar approved these changes

2023-03-29 10:34 UTC, merged